---

- name: Gather package facts
  package_facts:
  check_mode: no
  tags:
    - yum

- { import_tasks: keys.yml, tags: ['cvmfs', 'keys'] }
- { import_tasks: repos.yml, tags: ['cvmfs', 'repos'] }
- { import_tasks: users.yml, tags: ['cvmfs', 'users'] }
- { import_tasks: storage.yml, tags: ['cvmfs', 'storage'], when: cvmfs_client_configure_storage | bool }
- { import_tasks: packages.yml, tags: ['cvmfs', 'packages'] }
- { import_tasks: config.yml, tags: ['cvmfs', 'config'] }
- { import_tasks: test.yml, tags: ['cvmfs', 'test'] }

