---

- name: Install CVMFS client and configuration packages
  yum:
    name: "{{ ['cvmfs'] + cvmfs_auto_setup_package + cvmfs_fuse3_package + cvmfs_configuration }}"
  vars:
    cvmfs_auto_setup_package: "{{ ['cvmfs-auto-setup'] if cvmfs_auto_setup|bool else [] }}"
    cvmfs_fuse3_package: "{{ ['cvmfs-fuse3'] if cvmfs_use_fuse3|bool else [] }}"
