---

- name: Converge
  hosts: all
  become: true

  roles:
  - role: cvmfs_contrib.cvmfs_client
    vars:
      cvmfs_client_configure_storage: false
      cvmfs_cache_size: "1500"  # small cache size for CI
      cvmfs_http_proxy: "DIRECT"
